name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout the repository
        uses: "actions/checkout@v4"

      - name: ℹ️ Get integration information
        id: information
        run: |
          name=$(find custom_components/ -type d -maxdepth 1 | tail -n 1 | cut -d "/" -f2)
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: 🔢 Adjust version number
        shell: "bash"
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version#v}"
          jq --arg v "$version" '.version = $v' \
            "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/manifest.json" > tmp.json
          mv tmp.json "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/manifest.json"

      - name: 📦 ZIP the integration directory
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}"
          zip ${{ steps.information.outputs.name }}.zip -r ./

      - name: 📤 Upload the ZIP file to the release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/${{ steps.information.outputs.name }}.zip
